### ISSUE TITLE
DC motor node

### ISSUE THREAD

**Issue by Darshabafna** [SnappyRobotics/snappyTimeline#42]
Developing output nodes

**Comment by prajankya** [comment]
@Belavatagi you haven't done test for DC Motor, you have to study how arduino is simulated, as we had seen on some other package, and then test is in software how it works

**Comment by prajankya** [comment]
at SnappyRobotics/SnappyLogicNodes@05b678f96a85199a16c8c390e4ea67d11cd24e81
you only added loading test
